import java.util.regex.Matcher
import java.util.regex.Pattern

task toolChainCheck {
    def tree = fileTree(include: ['*.gradle'], dir: './')
    def hasError = false
    tree.each { File file ->

        println file
        def reader = new BufferedReader(new FileReader(file));
        def buffer = new StringBuffer();
        def str;
        while( (str=reader.readLine())!=null ){
            buffer.append(str)
            buffer.append("\n")
        }
        str = buffer.toString()

        def find = ["[\\s]*jackOptions", "[\\s]*retrolambda "]
        find.each { name ->
            Pattern ptn = Pattern.compile(name);
            Matcher matcher = ptn.matcher(str);
            if( matcher.matches() ){
                hasError = true
            }
        }
    }

    println ""
    if( hasError ) {
        println "[Warning] Android's default-tool-chain is Deactivate!!"
    } else {
        println "No Problem: Android's default-tool-chain is Active."
    }
    println ""
}
